#define principal main
#define arriba_espanya void
#define entero int
#define flotante float
#define cara char
#define doble double
#define sus return
#define si if
#define sino else
#define depende switch
#define caso case
#define roto break
#define sin default
#define espanya printf
#define viva_espanya puts
#define manolo scanf
#define santiago fgets
#define toro malloc
