#define hispania main
#define valladolid void
#define madrid int
#define canarias float
#define catalonia char
#define vallecas double
#define patria typedef
#define dios struct
#define cordoba const
#define don_bosco return
#define ifema if
#define elipa else
#define en_funcion_de switch
#define castellana case
#define renfe break
#define napolitana default
#define sevilla sizeof
#define formentera for
#define rajoy printf
#define viva_hispania puts
#define manolo scanf
#define santiago fgets
#define mallorca malloc
#define villa_real realloc
#define a_tope free
#define meco strcpy
#define segovia strlen
#define bomba getchar
